name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-preview:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Generate slug
        uses: rlespinasse/github-slug-action@v4
      - uses: pnpm/action-setup@v2
